# -*- coding: utf-8 -*-
"""Menu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Pn__JHVQQ6yBaK4Dedb_O-lTKxj-IWq
"""

import streamlit as st

# --- Personalización de diseño ---
st.markdown("""
<style>
    .stApp {
        background-color: #00FF00;
    }
    .css-1d391kg {
        color: #faf7f8;
    }
</style>
""", unsafe_allow_html=True)

st.title("Menú de enlaces")

# Diccionario con opciones y links
links = {
    "Horarios": "https://scheduler-eqbyudcqtuurxkcxe8epvw.streamlit.app/",
    "Repositorio": "https://videos-class-ntxornvewsnmrkyvsuc7yu.streamlit.app/",
    "App Bitcoin": "https://app-bitcoin-zdpaws8phg4pmnvyfatacf.streamlit.app/",
    "App VaR": "https://appvar-kj9zh5egahy4lfhwrkf732.streamlit.app/",
    "App RL": "https://b8rvvwhhdmfegkkcpwreoc.streamlit.app/",
    "Reto Actinver": "https://retoactinver-7ugnxpfgupkdufnskngbvg.streamlit.app/",
    "Multi Monte Carlo":"https://simulmc-kq7fbvqbafqnateomyp8qp.streamlit.app/",
    "Simulación Monte Carlo": "https://dr42zwffvmeo7pls3snkuv.streamlit.app/",
    "Juego Finance Trade": "https://gamemc-b5xmwf59skfzltrultxwnt.streamlit.app/",
    "Red Bitcoin": "https://redbitcoin-cjnu98svsavr74wwnbgqqx.streamlit.app/",
    "Oportunidades": "https://oportunidades-qrpe3unrhhfd2gn3aapepp.streamlit.app/",
    "Hooke": "https://alterno-vtw6bhga4gudyeqba5suui.streamlit.app/",
    "Second opinion": "https://segunda-ntrnial2zghui5zgdgncop.streamlit.app/",
    "Portfolio Óptimo": "https://portafolio-optimo-otqmf2ztv3f99wlwlhjkew.streamlit.app/",
    "Goool": "https://golcontadur-a-5ghwo56yuaqtpcklfbfuqj.streamlit.app/",
    "Bayesrs": "https://bayesrs-fwnqj5kbasqiyyqzdrt2ws.streamlit.app/",
    "LSTM": "https://colab.research.google.com/drive/11fgk1eoRfDgF9uM32lw-GN4eM2_TYyJY?usp=sharing",
    "Quiero Casa": "https://quierocasa.com.mx/",
    "Bayes GMEXICOB": "https://gmexico-2cizabuqy4fxx6pjg3puwe.streamlit.app/",
    "Lista 409": "https://asistencia409-443909246942.us-central1.run.app/",
    "Shopping": "https://shopping-v3mvgyrmt8u9nyftebqnee.streamlit.app/",
    "Bernoulli": "https://colab.research.google.com/drive/15-py0f9a_ioAJy3nJhk2kfFcsus_TIhY?usp=sharing",
    "Rendimientos": "https://colab.research.google.com/drive/1_CikKZh6PHS14xKAY0W3ymlLTduAe8fZ?usp=sharing",
    "Tipo de Cambio": "https://exchange-r68mzkn9bmgvfhket3fznp.streamlit.app/",
    "Pedido Óptimo": "https://e7r3qwij5erjhfbjifshss.streamlit.app/",
    "Game": "https://3hj5elrsp5xmisqkhfpusn.streamlit.app/",
    "Party": "https://janpw5rqpsqkkmre9tqdys.streamlit.app/",
    "Entrada": "https://entrada-r9hxucrpbp8q77hngjlh52.streamlit.app/",
    "Roptura": "https://colab.research.google.com/drive/10CQgFDQOStj57I3GR_8vTcYxo62H9L4z?usp=sharing",
    "Bayes_Map": "https://bayesmap-kgxsvqhpmtdfukvp6qhfez.streamlit.app/",
    "RL": "https://colab.research.google.com/drive/1GtWhlRMAIMcTWnRuPpAHoqR0ymaZhOso?usp=sharing",
    "Market Cap": "https://companiesmarketcap.com/assets-by-market-cap/",
    "Calendario Lunar": "https://www.calendario-365.mx/luna/calendario-lunar.html",
    "Trend": "https://colab.research.google.com/drive/1HALQGTxl6SpJaSawmpM-90SIMza7yIil?usp=sharing",
    "Quantumm Computing": "https://colab.research.google.com/drive/1f64ToI7oTxaMClB3uZDvf1LKELFiZXEd?usp=sharing",
    "Pedido": "https://pedido-44xztayv3phs8t2jmchmq8.streamlit.app/",
    "Probabilidad": "https://probabilidad-lc5nb3p6xetbsvadzjyk4y.streamlit.app/",
    "Rendimientos mensuales": "https://preciocierre-gwhq3lwwrabizqwtpynbje.streamlit.app/",
    "Galletita financiera": "https://galleta-bfmexnl9e76gglkaanadm3.streamlit.app/",
    "BMV": "https://appbmv-f9igvhnh5sc7wjax66ukjs.streamlit.app/",
    "Volatilidades": "https://colab.research.google.com/drive/1QzYhaLwjNyKB_8Vw13UvexFGZ1EbK8rl?usp=sharing",
    "CAPEX": "https://colab.research.google.com/drive/1MxxbXHsQyF0FGYaG39HcvFrAfJNQCGqf?usp=sharing",
    "Buen humor": "https://colab.research.google.com/drive/1DYDu9I4B6_OLlBdUkAmzoilBp-sKl7O0?usp=sharing",
    "Resorte": "https://colab.research.google.com/drive/1_o-yUIe1TpOs53zwa0yaY8njrc8345lW?usp=sharing",
    "Calendario": "https://es.tradingeconomics.com/country-list/unemployment-rate",
    "CETES": "https://www.cetesdirecto.com/sites/portal/inicio",
    "Gate": "https://gate-streamlit-443909246942.us-central1.run.app",
    "SPP": "https://colab.research.google.com/drive/1Hs_f7QPnywU6Q2XGyxyNfUGx4QkHGmSJ?usp=sharing",
    "Music": "https://5gaehenr8pbzfyadepdafg.streamlit.app/",
    "Alcohol": "https://alcohol-fqlvjbuf6rrr62dyeyqmjc.streamlit.app/",
    "Bayes": "https://colab.research.google.com/drive/1lOc_KbMZ3S3y1aA99zNPDe5qshNcjb9e?usp=sharing",
    "FED": "https://gmovmmbwsmkffrhsnurj8m.streamlit.app/",
    "Seguimiento Portafolio": "https://colab.research.google.com/drive/1PawFqbF9YJN5x3h1DZPGqXzDHcfwGIH6?usp=sharing",
    "Índice de Vivienda SHF": "https://b9cairxvwefxjbw9mnyepb.streamlit.app/",
    


}

# Menú desplegable
opcion = st.selectbox("Selecciona una opción:", list(links.keys()))

# Mostrar botón con enlace
st.markdown(f"[Ir a {opcion}]({links[opcion]})", unsafe_allow_html=True)
